Official Julia image

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,14 +17,14 @@ stages:
 update-julia:
   image: julia:1.7
   # tags:
-  #   - md705
+  #   - your_runner
   stage: update:julia
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule"
   variables:
     JULIA_PKG_PRECOMPILE_AUTO: 0
   script:
-    - apt-get update -qq && apt-get install -y --no-install-recommends git
+    - apt-get update && apt-get install -y --no-install-recommends git
     - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
     # Open a MR when there is a update, requires GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
     - |
@@ -55,7 +55,7 @@ build-docker:
   variables:
     IMG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   # tags:
-  #   - md705
+  #   - your_runner
   services:
     - docker:dind
   stage: build:docker
@@ -70,6 +70,7 @@ build-docker:
         - Project.toml
         - Manifest.toml
         - .gitlab-ci.yml
+
   script:
     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
     - docker pull $CI_REGISTRY_IMAGE:latest || true
@@ -85,15 +86,9 @@ build-docker:
       --tag $IMG
       -f docker/Dockerfile
       .
-    # main -> latest; others -> branch name
-    - |
-      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
-        echo "Latest tag for the default branch"
-        docker tag $IMG $CI_REGISTRY_IMAGE:latest
-      else
-        echo "Branch tag for the others"
-        docker tag $IMG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
-      fi
+    # main -> latest
+    - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && docker tag $IMG $CI_REGISTRY_IMAGE:latest
+    - docker tag $IMG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
     - docker push --all-tags $CI_REGISTRY_IMAGE
 
 .push-docker:
@@ -118,11 +113,14 @@ push-tag-docker:
   variables:
     TAG: $CI_COMMIT_TAG
 
-.build-notebooks:
-  image: $CI_REGISTRY_IMAGE:latest
-  tags:
-    - md705
+build-notebooks:
+  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
+  # tags:
+  #   - your_runner
   stage: build:notebooks
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
   cache:
     - key:
         files:
@@ -140,22 +138,18 @@ push-tag-docker:
       - docs/_build/
     expire_in: 1 day
 
-mr-notebooks:
-  extends: .build-notebooks
-  rules:
-    - if: $CI_MERGE_REQUEST_IID
-  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
-
 pages:
-  extends: .build-notebooks
+  image: alpine:latest
+  stage: deploy
+  cache: []
+  variables:
+    GIT_STRATEGY: none
   rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
   script:
-    # Uncomment if you want parallel notebook execution
-    # - find docs -type f -name "*.ipynb" -print0 | parallel -0 -j2 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=julia-${JL_MAJOR} --execute --inplace {}
-    - jupyter-book build docs
+    - apk add --no-cache gzip brotli
     - mv docs/_build/html public
-    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec brotli -f -k {} \; || echo 'Compression failed. Skipping...'
+    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec  -f -k {} \; || echo 'Compression failed. Skipping...'
   artifacts:
     paths:
       - public
