stages

diff --git a/.github/workflows/ci-parallel.yml b/.github/workflows/ci-parallel.yml
--- a/.github/workflows/ci-parallel.yml
+++ b/.github/workflows/ci-parallel.yml
@@ -15,8 +15,8 @@ env:
   JOBS: 8
 
 jobs:
-  ci:
-    name: CI (self-hosted)
+  execute:
+    name: Execute notebooks (self-hosted)
     runs-on: self-hosted
     steps:
       - name: Checkout repository
@@ -26,7 +26,7 @@ jobs:
         with:
           python-version: '3.10'
       - name: Install matplotlib
-        run: pip install -U matplotlib jupyter-book
+        run: pip install -U matplotlib nbconvert
       - name: Read Julia version
         uses: SebRollen/toml-action@v1.0.2
         id: read_toml
@@ -39,13 +39,6 @@ jobs:
         uses: julia-actions/setup-julia@v1
         with:
           version: ${{ env.jlver }}
-      # - name: Cache Julia deps
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ~/.julia
-      #     key: ${{ runner.os }}-julia-${{ env.jlver }}-${{ env.JULIA_CACHE_NUM }}-${{ hashFiles('**/Manifest.toml') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-julia-${{ env.jlver }}-${{ env.JULIA_CACHE_NUM }}-
       - name: Install Julia deps
         run: |
           julia --color=yes --project="" -e 'import Pkg; Pkg.add("IJulia"); using IJulia; installkernel("Julia", "--project=@.", env=Dict("JULIA_NUM_THREADS"=>"auto"))'
@@ -59,13 +52,60 @@ jobs:
           {} ::: docs/*.ipynb
       - name: Show execution results
         run: cat /tmp/log
+      - name: Upload Notebook
+        uses: actions/upload-artifact@v3
+        with:
+          name: notebook
+          path: docs/*.ipynb
+
+  jupyter-book:
+    needs: execute
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/sosiristseng/docker-jupyterbook:latest
+    # store success output flag for the ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      - name: Download notebooks
+        uses: actions/download-artifact@v3
+        with:
+          path: out/
+      - name: Move notebooks
+        run: find out/ -type f -iname '*.ipynb' -exec mv -t docs/ {} +
       - name: Build website
-        run: jupyter-book build docs/ --keep-going -v
-      - name: Upload page artifact
+        run: jupyter-book build docs/
+      - name: Set output flag
+        id: setoutput
+        run: echo "success=true" >> $GITHUB_OUTPUT
+      - name: Upload pages artifact
         if: github.ref == 'refs/heads/main'
         uses: actions/upload-pages-artifact@v1
         with:
           path: docs/_build/html
+
+  # Jobb for GitHub status check
+  # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  ci:
+    name: CI (parallel)
+    needs: jupyter-book
+    runs-on: ubuntu-latest
+    if: always() # always run, so we never skip the check
+    steps:
+      # pass step only when output of previous jupyter-book job is set
+      # in case at least one of the execution fails, jupyter-book is skipped
+      # and the output will not be set, which will then cause the ci job to fail
+      - run: |
+          passed="${{ needs.jupyter-book.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
 
   # Deployment job
   deploy:
